version: '3'

services:
  brevets:
    build: brevets/.
    command: python flask_brevets.py
    container_name: brevets
    depends_on:
      - db
    ports:
      - "5000:5000"
    restart: unless-stopped

  db:
    container_name: mongodb
    image: mongo:5.0.5
    restart: unless-stopped
